### ISSUE TITLE
remove zero weight edges instead of throwing error

### ISSUE THREAD

**Issue by dxyzx0** [CharJon/ScientificMaxcutSolver#1]
I have encountered several instances involving graphs with zero-weight edges. Removing these edges theoretically should not impact the max cut solution, even though it might result in some partitions becoming disconnected.

Could you please clarify if there is a specific reason why the solver [throws errors](https://github.com/CharJon/ScientificMaxcutSolver/blob/b541e1f5ea4ab1b5d15a960d83acc98c51491aa6/src/io/io.cpp#L141) when encountering zero-weight edges? Is there a particular aspect of the implementation or theoretical consideration that requires these edges to be treated differently?

Thank you for your great work.

**Comment by CharJon** [comment]
Hi,
edges of weight zero can be removed / added without any impact on (optimal) solutions for MaxCut, you are correct.
The only reason for treating zero weight edges as an error is the [format specification](http://mcsparse.uni-bonn.de/formats.html) of our [online solver](http://mcsparse.uni-bonn.de/). For ".mc" files, zero weight edges are not allowed (they sometimes indicate errors in scripts generating graphs).
Reading in graphs in 1-indexed ".wel", will not throw errors for zero weight edges.
I hope this helps.

**Comment by dxyzx0** [comment]
Got it. Thanks for the quick response.
